SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

MAP_WIDTH = 20000
MAP_HIGHT = 10000

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 600
PLAYER_SHOOT_SPEED = 1500
PLAYER_SHOOT_COOLDOWN = 0.5
PLAYER_SHOT_RADIUS = 5
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.3  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS


ENEMY_SPAWN_RATE = 2
ENEMY_X_LINE = 1000

ENEMY_RADIUS = 50
ENEMY_SPEED = 600
ENEMY_SHOOT_SPEED = 200
ENEMY_SHOOT_COOLDOWN = 2
ENEMY_SHOT_RADIUS = 20

WEAPON_SPEED = [0.5, 0.4, 0.3, 0.2, 0.1]
PROJECTILES = [1, 2, 3]
DIRECTIONS = [1, 2, 4]
ENEMY_SPEED = [200, 400, 600]

PLAYER_WEAPON_SPEED = [0.5, 0.4, 0.3, 0.2, 0.1]
PROJECTILES = [1, 2, 3]
DIRECTIONS = [1, 2, 4]
PLAYER_SPEED = [200, 400, 600]


POWER_UP = ["dash", "piercing"]
GAME_CONSTANTS = {'player': {'weapon': {'speed': PLAYER_WEAPON_SPEED, 'projectiles': PROJECTILES},
                            'ship': {'speed': PLAYER_SPEED, 'power_up': POWER_UP},
                            },
                  'enemy': {'weapon': {'speed': WEAPON_SPEED},
                            'ship': {'speed': PLAYER_SPEED, 'spawn_rate': POWER_UP},
                            },
                    }